dependencies:
  build:

build_targets:
  - name: default
    environment:
      - TRAVIS_OS_NAME=linux
      - CC=clang
      - BUILD_CONFIGURATION=debug
      - LLVM_VERSION=3.4.2
      - TARGET_CPU=amd64
    commands:
      - apt-get update
      - apt-get install -y build-essential g++  clang-6.0
      - ./source
      - ./i/travis/install-linux.sh
      - ./ci/travis/download-llvm.sh

ci:
  builds:
    - name: build
      build_target: default